/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.jrc.mp;

import br.jrc.mp.lib.Ambiente;
import br.jrc.mp.lib.Robo;
import br.jrc.utilis.Funcoes;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author jrcorrea
 */
public class fraExecucao extends javax.swing.JFrame {
          
    private Robo meuRobo;    
    private meuAmbiente obAmbiente = null;
    private String ArquivoRobo=null;    
    private fraTela tela;
    private Timer timerRelogio;
    private MyTela[][] mapAtual;
    
    private long loTempo;
    private int indice = 1;
    
    class TaskRelogio extends TimerTask {   
        
        public void run() {   
            if (!obAmbiente.isRoboFinalizou() || obAmbiente.getQtdOperacoes()>indice){
                labTempo.setText(Funcoes.getTempoFormatado(System.currentTimeMillis() - loTempo));
                
                int[] dados = (int[]) obAmbiente.getDados(indice);
                String log = (String) obAmbiente.getLog(indice);
                int[] movimento= (int[]) obAmbiente.getMovimento(indice);            
                byte[][] limpeza= (byte[][]) obAmbiente.getLimpeza(indice);
                byte[][] mapeamento= (byte[][]) obAmbiente.getMapeamento(indice);
            
                if (movimento!=null){                                                                                          
                     mapAtual[movimento[0]][movimento[1]].setImagem((byte) movimento[2]); 
                     mapAtual[movimento[3]][movimento[4]].setImagem((byte) movimento[5]); 
                }

                if (dados!=null){
                    labNivelCacamba.setText(String.valueOf((dados[1]+dados[2]+dados[3]+dados[4]+dados[5])));
                    labNivelBateria.setText(String.valueOf(dados[0]));
                    txtLog.insert(log,0);
                    labNivelCacambaTotal.setText(dados[1] + "me " +  dados[2] + "or " + dados[3] + "pa " + dados[4] + "pl " + dados[5] +  "vi  descarregados " + dados[6] + "me " +  dados[7] + "or " + dados[8] + "pa " + dados[9] + "pl " + dados[10] +  "vi "  );
                    labQtdOperacoes.setText(String.valueOf(indice));
                    indice++;
                }

                if ( mapeamento!=null){
                    tela.setMapeamento(mapeamento); 
                }
                if ( limpeza!=null){
                    tela.setLimpeza(limpeza); 
                }
                tela.atualizar();
                timerRelogio.schedule(new TaskRelogio(), 40);
            }else{
                butExecutar1.setEnabled(true);
                butAdiantar.setEnabled(true);
                butPrimeiro.setEnabled(true);
                butUltimo.setEnabled(true);
                butVoltar.setEnabled(true);

                txtClasse.setEnabled(true);
                txtBateriaNivelMaximo.setEnabled(true);
                txtCacambaNivelMaximo.setEnabled(true);
                meuRobo = null;
            }
        }
    }
    /**
     * Creates new form fraExecucao
     */
    public fraExecucao( String arquivoRobo) {
        
        initComponents();  
        
        timerRelogio = new Timer();
                                                     
        ArquivoRobo=arquivoRobo;      
        int inLargura = fraPrincipal.getLargura();
        int inAltura = fraPrincipal.getAltura();
        if (inAltura>inLargura){
            txtBateriaNivelMaximo.setText(String.valueOf(inAltura*8));
        }else{
            txtBateriaNivelMaximo.setText(String.valueOf(inLargura*8));
        }
        MyTela[][] tempTela =fraPrincipal.getMapa();
        int inLixo=0;
        for (int i=0;i<tempTela.length;i++)
            for (int j=0;j<tempTela[0].length;j++)
                if (tempTela[i][j].getValor()==Ambiente.METAL || tempTela[i][j].getValor()==Ambiente.ORGANICO || tempTela[i][j].getValor()==Ambiente.PAPEL || tempTela[i][j].getValor()==Ambiente.PLASTICO || tempTela[i][j].getValor()==Ambiente.VIDRO)
                    inLixo++;
        if (inLixo>4){
            txtCacambaNivelMaximo.setText(String.valueOf((int)inLixo/4));
        }else{
            txtCacambaNivelMaximo.setText(String.valueOf(inLixo));
        }
        
                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labNomeRobo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labNomeRobo1 = new javax.swing.JLabel();
        labNomeRobo2 = new javax.swing.JLabel();
        labNivelBateria = new javax.swing.JLabel();
        labNivelMaximoBateria = new javax.swing.JLabel();
        labNomeRobo4 = new javax.swing.JLabel();
        labNomeRobo3 = new javax.swing.JLabel();
        labNivelCacamba = new javax.swing.JLabel();
        labNivelMaximoCacamba = new javax.swing.JLabel();
        labNivelCacambaTotal = new javax.swing.JLabel();
        labTempo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        labQtdOperacoes = new javax.swing.JLabel();
        labNomeRobo6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtClasse = new javax.swing.JTextField();
        butVoltar = new javax.swing.JButton();
        labMensagem = new javax.swing.JLabel();
        labNomeRobo5 = new javax.swing.JLabel();
        txtBateriaNivelMaximo = new javax.swing.JTextField();
        labNomeRobo8 = new javax.swing.JLabel();
        txtCacambaNivelMaximo = new javax.swing.JTextField();
        butExecutar1 = new javax.swing.JButton();
        butAdiantar = new javax.swing.JButton();
        butPrimeiro = new javax.swing.JButton();
        butUltimo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teste de Robor - Mapeamento de Ambiente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Robo"));

        labNomeRobo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labNomeRobo.setText("Nome do Robo");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Níveis"));

        labNomeRobo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labNomeRobo1.setText("Bateria");

        labNomeRobo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labNomeRobo2.setText("máx.");

        labNivelBateria.setBackground(new java.awt.Color(153, 204, 255));
        labNivelBateria.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        labNivelBateria.setForeground(new java.awt.Color(0, 0, 102));
        labNivelBateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNivelBateria.setOpaque(true);

        labNivelMaximoBateria.setBackground(new java.awt.Color(255, 255, 204));
        labNivelMaximoBateria.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        labNivelMaximoBateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNivelMaximoBateria.setOpaque(true);

        labNomeRobo4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labNomeRobo4.setText("máx.");

        labNomeRobo3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labNomeRobo3.setText("Caçamba");

        labNivelCacamba.setBackground(new java.awt.Color(153, 204, 255));
        labNivelCacamba.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        labNivelCacamba.setForeground(new java.awt.Color(0, 0, 102));
        labNivelCacamba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNivelCacamba.setText("150");
        labNivelCacamba.setOpaque(true);

        labNivelMaximoCacamba.setBackground(new java.awt.Color(255, 255, 204));
        labNivelMaximoCacamba.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        labNivelMaximoCacamba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNivelMaximoCacamba.setOpaque(true);

        labNivelCacambaTotal.setBackground(new java.awt.Color(153, 204, 255));
        labNivelCacambaTotal.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        labNivelCacambaTotal.setForeground(new java.awt.Color(0, 0, 102));
        labNivelCacambaTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNivelCacambaTotal.setOpaque(true);

        labTempo.setBackground(new java.awt.Color(255, 255, 204));
        labTempo.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        labTempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTempo.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labNomeRobo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labNomeRobo3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labNivelBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labNivelCacamba, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labNomeRobo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labNomeRobo2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labNivelMaximoCacamba, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labNivelCacambaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labNivelMaximoBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labNomeRobo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labNivelBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labNomeRobo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labNivelMaximoBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labNomeRobo3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labNivelCacamba, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labNomeRobo4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labNivelMaximoCacamba, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labNivelCacambaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));
        jPanel5.setPreferredSize(new java.awt.Dimension(385, 385));

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        labQtdOperacoes.setBackground(new java.awt.Color(153, 204, 255));
        labQtdOperacoes.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        labQtdOperacoes.setForeground(new java.awt.Color(0, 51, 102));
        labQtdOperacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labQtdOperacoes.setOpaque(true);

        labNomeRobo6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labNomeRobo6.setText("Operações");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labNomeRobo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labNomeRobo6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labQtdOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labQtdOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labNomeRobo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labNomeRobo6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));

        jLabel1.setText("Classe");

        txtClasse.setText("br.jrc.robo.jrcRoboA2");

        butVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anterior.png"))); // NOI18N
        butVoltar.setToolTipText("Anterior");
        butVoltar.setAlignmentY(0.0F);
        butVoltar.setMargin(null);
        butVoltar.setMaximumSize(null);
        butVoltar.setMinimumSize(null);
        butVoltar.setName(""); // NOI18N
        butVoltar.setPreferredSize(new java.awt.Dimension(24, 24));
        butVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVoltarActionPerformed(evt);
            }
        });

        labMensagem.setBackground(new java.awt.Color(255, 255, 204));
        labMensagem.setForeground(new java.awt.Color(102, 102, 102));
        labMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labMensagem.setOpaque(true);

        labNomeRobo5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labNomeRobo5.setText("Bateria");

        txtBateriaNivelMaximo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBateriaNivelMaximo.setText("1000");

        labNomeRobo8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labNomeRobo8.setText("Caçamba");

        txtCacambaNivelMaximo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCacambaNivelMaximo.setText("50");

        butExecutar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butExecutar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/executar.png"))); // NOI18N
        butExecutar1.setToolTipText("Executar");
        butExecutar1.setAlignmentY(0.0F);
        butExecutar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butExecutar1.setMargin(null);
        butExecutar1.setMaximumSize(new java.awt.Dimension(24, 24));
        butExecutar1.setMinimumSize(new java.awt.Dimension(24, 24));
        butExecutar1.setName(""); // NOI18N
        butExecutar1.setPreferredSize(new java.awt.Dimension(24, 24));
        butExecutar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExecutar1ActionPerformed(evt);
            }
        });

        butAdiantar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proximo.png"))); // NOI18N
        butAdiantar.setToolTipText("Próximo");
        butAdiantar.setMargin(null);
        butAdiantar.setPreferredSize(new java.awt.Dimension(24, 24));
        butAdiantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAdiantarActionPerformed(evt);
            }
        });

        butPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/primeiro.png"))); // NOI18N
        butPrimeiro.setToolTipText("Primeira Operação");
        butPrimeiro.setAlignmentY(0.0F);
        butPrimeiro.setMargin(null);
        butPrimeiro.setMaximumSize(null);
        butPrimeiro.setMinimumSize(null);
        butPrimeiro.setPreferredSize(new java.awt.Dimension(24, 24));
        butPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPrimeiroActionPerformed(evt);
            }
        });

        butUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ultimo.png"))); // NOI18N
        butUltimo.setToolTipText("Última Operação");
        butUltimo.setMargin(null);
        butUltimo.setMaximumSize(null);
        butUltimo.setMinimumSize(null);
        butUltimo.setPreferredSize(new java.awt.Dimension(24, 24));
        butUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBateriaNivelMaximo)
                    .addComponent(labNomeRobo5, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCacambaNivelMaximo)
                    .addComponent(labNomeRobo8, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butExecutar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butAdiantar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
            .addComponent(labMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labNomeRobo5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labNomeRobo8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBateriaNivelMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCacambaNivelMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butAdiantar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(butExecutar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void butVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVoltarActionPerformed
                
        
        if (obAmbiente.voltarOperacao()){
            butAdiantar.setEnabled(true);
        }else{
            butVoltar.setEnabled(false);
        }        
                     
    }//GEN-LAST:event_butVoltarActionPerformed

    private void butExecutar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExecutar1ActionPerformed
        butExecutar1.setEnabled(false);
        butAdiantar.setEnabled(false);
        butPrimeiro.setEnabled(false);
        butUltimo.setEnabled(false);
        butVoltar.setEnabled(false);

        txtClasse.setEnabled(false);
        txtBateriaNivelMaximo.setEnabled(false);
        txtCacambaNivelMaximo.setEnabled(false); 
        meuRobo = Funcoes.roboLoad(ArquivoRobo, txtClasse.getText());
         
        if (meuRobo!=null){
            
            txtLog.setText(null);
            labMensagem.setText("Robo " + meuRobo.getNome() + " Carregado " );
            labNomeRobo.setText(meuRobo.getNome());            
            
            int inBateriaNivelMaximo =  Integer.valueOf(txtBateriaNivelMaximo.getText());
            int inCacambaNivelMaximo =  Integer.valueOf(txtCacambaNivelMaximo.getText());
            
            tela = new fraTela(fraPrincipal.getMapa(), fraPrincipal.getImagens());            
            //link para atualizar a tela                                     
            mapAtual = tela.getMapa();
            
            int linha, coluna;
            do{
                 linha = (int) (Math.random() * mapAtual.length); 
                coluna = (int) (Math.random() * mapAtual[0].length);
            }while(mapAtual[linha][coluna].getValor()!=Ambiente.CHAO);
            
            mapAtual[linha][coluna].setImagem(Ambiente.ROBO);                                                       

            // meuAmbiente(MyTela[][] mapa, JPanel telaPrincipal, int linhaRobo, int colunaRobo,int qtdLinhas, int qtdColunas, long tempoRefresh, int nivelInicialBateria, int nivelMaximoBateria, int capacidadeCacamba, Robo robo){    
            labNivelMaximoBateria.setText(txtBateriaNivelMaximo.getText());
            labNivelMaximoCacamba.setText(txtCacambaNivelMaximo.getText());       

            obAmbiente = new meuAmbiente( mapAtual,  linha, coluna, inBateriaNivelMaximo, inCacambaNivelMaximo, meuRobo   );
                                    
            tela.setVisible(true);
            
            new Thread(obAmbiente).start();
            
            timerRelogio.schedule(new TaskRelogio(), 40);
            
            labTempo.setText("");
            loTempo = System.currentTimeMillis();
                        
            
            }else{
                butExecutar1.setEnabled(true);
                butAdiantar.setEnabled(true);
                butPrimeiro.setEnabled(true);
                butUltimo.setEnabled(true);
                butVoltar.setEnabled(true);
                txtClasse.setEnabled(true);
                txtBateriaNivelMaximo.setEnabled(true);
                txtCacambaNivelMaximo.setEnabled(true);
                JOptionPane.showMessageDialog(this,  "Não foi possivel carregar o Robo",   "Classe não Localizada",    JOptionPane.ERROR_MESSAGE);
                labMensagem.setText("Não foi possivel carregar o Robo " );
            }
    }//GEN-LAST:event_butExecutar1ActionPerformed

    private void butAdiantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAdiantarActionPerformed
        
        if (obAmbiente.adiantarOperacao()){
            butVoltar.setEnabled(true);
        }else{
            butAdiantar.setEnabled(false);
        }
        
    }//GEN-LAST:event_butAdiantarActionPerformed

    private void butPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPrimeiroActionPerformed
        obAmbiente.primeiraOperacao();
        butVoltar.setEnabled(false);
        butAdiantar.setEnabled(true);
    }//GEN-LAST:event_butPrimeiroActionPerformed

    private void butUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUltimoActionPerformed
         obAmbiente.ultimaOperacao();
         butAdiantar.setEnabled(false);
         butVoltar.setEnabled(true);
    }//GEN-LAST:event_butUltimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdiantar;
    private javax.swing.JButton butExecutar1;
    private javax.swing.JButton butPrimeiro;
    private javax.swing.JButton butUltimo;
    private javax.swing.JButton butVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labMensagem;
    private javax.swing.JLabel labNivelBateria;
    private javax.swing.JLabel labNivelCacamba;
    private javax.swing.JLabel labNivelCacambaTotal;
    private javax.swing.JLabel labNivelMaximoBateria;
    private javax.swing.JLabel labNivelMaximoCacamba;
    private javax.swing.JLabel labNomeRobo;
    private javax.swing.JLabel labNomeRobo1;
    private javax.swing.JLabel labNomeRobo2;
    private javax.swing.JLabel labNomeRobo3;
    private javax.swing.JLabel labNomeRobo4;
    private javax.swing.JLabel labNomeRobo5;
    private javax.swing.JLabel labNomeRobo6;
    private javax.swing.JLabel labNomeRobo8;
    private javax.swing.JLabel labQtdOperacoes;
    private javax.swing.JLabel labTempo;
    private javax.swing.JTextField txtBateriaNivelMaximo;
    private javax.swing.JTextField txtCacambaNivelMaximo;
    private javax.swing.JTextField txtClasse;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
