/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.jrc.mp;

import br.jrc.mp.lib.Ambiente;
import br.jrc.utilis.Funcoes;
import br.jrc.utilis.selecaoTipoArquivo;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Properties;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author jrcorrea
 */
public class fraPrincipal extends javax.swing.JFrame {
    private static MyTela[][] mapAtual = null;
    private String stCaminhoMapas ="D:\\Google Drive\\Dropbox\\mapa40x30.jrcmaps";
    private String stCaminhoRobo="D:\\Google Drive\\Dropbox\\java\\jrcMapeamentoPesquisa\\jrcRobo\\dist";
    
    private int qtdColunas;
    private int qtdLinhas;
    private byte Valor = Ambiente.CHAO;    
    private static Icon[] Imagens= new Icon[16];    
    
    // Create a File object on the root of the directory containing the class file
    
    public static MyTela[][] getMapa(){
        return mapAtual;
    }
    
    public static int getAltura(){
        return mapAtual.length;
    }
    
    public static int getLargura(){
        return  mapAtual[0].length;
    }
    public static Icon getImagem(int indice){
        return Imagens[indice];
    }
    
    public static Icon[] getImagens(){
        return Imagens;
    }
    
    
     
    /**
     * Creates new form fraPrincipal
     */
    public fraPrincipal() {
        initComponents();                
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);                   
        
        Imagens[Ambiente.BORDA] = butBorda.getIcon();
        Imagens[Ambiente.CARREGADOR] = butCarregador.getIcon();
        Imagens[Ambiente.CHAO] = butChao.getIcon();
        Imagens[Ambiente.COLETOR_METAL_AMARELA] = butMetalAmarelo.getIcon();
        Imagens[Ambiente.COLETOR_PAPEL_AZUL] = butPapelAzul.getIcon();
        Imagens[Ambiente.COLETOR_ORGANICO_MAROM] = butOrganicoMarom.getIcon();
        Imagens[Ambiente.COLETOR_VIDRO_VERDE] = butVidroVerde.getIcon();
        Imagens[Ambiente.COLETOR_PLASTICO_VERMELHA] = butPlasticoVermelho.getIcon();
        Imagens[Ambiente.METAL] = butMetal.getIcon();
        Imagens[Ambiente.OBSTACULO] = butObstaculo.getIcon();
        Imagens[Ambiente.ORGANICO] = butOrganico.getIcon();
        Imagens[Ambiente.PAPEL] = butPapel.getIcon();
        Imagens[Ambiente.PLASTICO] = butPlastico.getIcon();
        Imagens[Ambiente.VIDRO] = butVidro.getIcon();
        Imagens[Ambiente.ROBO] = butRobo.getIcon();
        butRobo.setVisible(false);                
        butCarregador.setVisible(false);    
        
        Properties prop = new Properties();
	InputStream input = null;
 
	try { 
		input = new FileInputStream("jrcMP.properties"); 
		prop.load(input); 		
		String stTemp = prop.getProperty("mapas_caminho");
                if(stTemp!=null) stCaminhoMapas = stTemp;
		stTemp = prop.getProperty("robo_caminho");
		if(stTemp!=null) stCaminhoRobo = stTemp;
                input.close();
	} catch (Exception ex) {}
                   
    }
    
    private void savePropriedades(){
        Properties prop = new Properties();
        OutputStream output = null;

        try {
            output = new FileOutputStream("jrcMP.properties");

            // set the properties value
            prop.setProperty("mapas_caminho", stCaminhoMapas);
            prop.setProperty("robo_caminho", stCaminhoRobo);

            // save properties to project root folder
            prop.store(output, null);
            output.close();
        } catch (Exception io) {      
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radComandos = new javax.swing.ButtonGroup();
        panPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLargura = new javax.swing.JTextField();
        butGerar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        butCarregador = new javax.swing.JToggleButton();
        butMetalAmarelo = new javax.swing.JToggleButton();
        butPapelAzul = new javax.swing.JToggleButton();
        butMetal = new javax.swing.JToggleButton();
        butOrganico = new javax.swing.JToggleButton();
        butPapel = new javax.swing.JToggleButton();
        butPlastico = new javax.swing.JToggleButton();
        butVidro = new javax.swing.JToggleButton();
        butChao = new javax.swing.JToggleButton();
        butVidroVerde = new javax.swing.JToggleButton();
        butOrganicoMarom = new javax.swing.JToggleButton();
        butPlasticoVermelho = new javax.swing.JToggleButton();
        butBorda = new javax.swing.JToggleButton();
        butObstaculo = new javax.swing.JToggleButton();
        butRobo = new javax.swing.JToggleButton();
        labMensagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAquivo = new javax.swing.JMenu();
        mnuAbrir = new javax.swing.JMenuItem();
        mnuNovo = new javax.swing.JMenuItem();
        mnuSalvar = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuCarregarRobo = new javax.swing.JMenuItem();
        mnuAvaliar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JrcRobo Finding");
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                resizeTela(evt);
            }
        });

        panPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Mapa"));
        panPrincipal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                panPrincipalComponentResized(evt);
            }
        });
        panPrincipal.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                panPrincipalAncestorResized(evt);
            }
        });

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));

        jLabel1.setText("Largura");

        txtLargura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLargura.setText("10");

        butGerar.setText("Gerar");
        butGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGerarActionPerformed(evt);
            }
        });

        jLabel2.setText("Altura");

        txtAltura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAltura.setText("10");

        butCarregador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tomada.png"))); // NOI18N
        butCarregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCarregadorActionPerformed(evt);
            }
        });

        butMetalAmarelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lixeira_amarela.png"))); // NOI18N
        butMetalAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMetalAmareloActionPerformed(evt);
            }
        });

        butPapelAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lixeira_azul.png"))); // NOI18N
        butPapelAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPapelAzulActionPerformed(evt);
            }
        });

        butMetal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metal.png"))); // NOI18N
        butMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMetalActionPerformed(evt);
            }
        });

        butOrganico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/organicol.png"))); // NOI18N
        butOrganico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOrganicoActionPerformed(evt);
            }
        });

        butPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/papel.png"))); // NOI18N
        butPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPapelActionPerformed(evt);
            }
        });

        butPlastico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plastico.png"))); // NOI18N
        butPlastico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPlasticoActionPerformed(evt);
            }
        });

        butVidro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidro.png"))); // NOI18N
        butVidro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVidroActionPerformed(evt);
            }
        });

        butChao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piso.png"))); // NOI18N
        butChao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butChaoActionPerformed(evt);
            }
        });

        butVidroVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lixeira_verde.png"))); // NOI18N
        butVidroVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVidroVerdeActionPerformed(evt);
            }
        });

        butOrganicoMarom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lixeira_marrom.png"))); // NOI18N
        butOrganicoMarom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOrganicoMaromActionPerformed(evt);
            }
        });

        butPlasticoVermelho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lixeira_vermelhar.png"))); // NOI18N
        butPlasticoVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPlasticoVermelhoActionPerformed(evt);
            }
        });

        butBorda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/borda.png"))); // NOI18N
        butBorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBordaActionPerformed(evt);
            }
        });

        butObstaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obstaculo.png"))); // NOI18N
        butObstaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butObstaculoActionPerformed(evt);
            }
        });

        butRobo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robo.png"))); // NOI18N
        butRobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRoboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(butGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butBorda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butChao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butCarregador, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butMetal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butOrganico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butPlastico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butVidro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butMetalAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butOrganicoMarom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butPapelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butPlasticoVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butVidroVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butRobo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butGerar))
                    .addComponent(butCarregador, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butMetalAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butPapelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butMetal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butOrganico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butPlastico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butVidro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butChao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butVidroVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butOrganicoMarom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butPlasticoVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butBorda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butRobo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mnuAquivo.setText("Mapas");

        mnuAbrir.setText("Abrir");
        mnuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbrirActionPerformed(evt);
            }
        });
        mnuAquivo.add(mnuAbrir);

        mnuNovo.setText("Novo");
        mnuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovoActionPerformed(evt);
            }
        });
        mnuAquivo.add(mnuNovo);

        mnuSalvar.setText("Salvar");
        mnuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalvarActionPerformed(evt);
            }
        });
        mnuAquivo.add(mnuSalvar);

        mnuSair.setText("Sair");
        mnuAquivo.add(mnuSair);

        jMenuBar1.add(mnuAquivo);

        jMenu2.setText("Robos");

        mnuCarregarRobo.setText("Carregar");
        mnuCarregarRobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCarregarRoboActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCarregarRobo);

        mnuAvaliar.setText("Avaliar");
        mnuAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAvaliarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAvaliar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void prepararMapa(){
        panPrincipal.removeAll();
        qtdColunas = Integer.valueOf(txtLargura.getText()); 
        qtdLinhas= Integer.valueOf(txtAltura.getText()); 
        
        txtLargura.setEditable(false);
        txtAltura.setEditable(false);
        
        int altura = (int) (((panPrincipal.getHeight()*0.95)-qtdLinhas+1)/qtdLinhas);
        int largura = (int) (((panPrincipal.getWidth()*0.95)-qtdColunas+1)/qtdColunas);        
        
        mapAtual = new MyTela[qtdLinhas][qtdColunas];
        
        int LarguraAltura;
        if (altura<largura){
            LarguraAltura = altura;
        }else{
            LarguraAltura = largura;
        }
        
        for (int i=0;i<qtdLinhas; i++)            
            for (int j=0;j<qtdColunas;j++){
                mapAtual[i][j] = new MyTela(Imagens);                
                
                mapAtual[i][j].setBounds( (j*LarguraAltura)+11, (i*LarguraAltura)+31, LarguraAltura,LarguraAltura);  
                if(i==0 || j ==0 || i==(qtdLinhas-1) || j == (qtdColunas-1) ){                    
                    mapAtual[i][j].setFixo();
                    mapAtual[i][j].setImagem(Ambiente.BORDA);
                    mapAtual[i][j].setIcon( Funcoes.getScaledImage(butBorda.getIcon(),LarguraAltura,LarguraAltura));
                }else{                    
                    mapAtual[i][j].setImagem(Ambiente.CHAO);
                    mapAtual[i][j].setIcon(Funcoes.getScaledImage(butChao.getIcon(),LarguraAltura,LarguraAltura));
                }                
                
                mapAtual[i][j].setVisible(true);
                mapAtual[i][j].addMouseListener(clickBotao);
                panPrincipal.add(mapAtual[i][j]);                 
                
            }
        
        panPrincipal.repaint(); 
    }
    private void butGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGerarActionPerformed
        prepararMapa();  
    }//GEN-LAST:event_butGerarActionPerformed

    private void resizeTela(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_resizeTela
        

    }//GEN-LAST:event_resizeTela

    private void panPrincipalAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_panPrincipalAncestorResized
    }//GEN-LAST:event_panPrincipalAncestorResized

    private void mnuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovoActionPerformed
        
        if (mapAtual==null) return;
        
        for (int i=0; i<qtdLinhas;i++){
            for(int j=0;j<qtdColunas;j++){
                mapAtual[i][j] = null;
            }
        }
        mapAtual = null;
        
        panPrincipal.removeAll();
        panPrincipal.repaint();
        
        txtLargura.setEditable(true);
        txtAltura.setEditable(true);
        
    }//GEN-LAST:event_mnuNovoActionPerformed

    private void mnuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalvarActionPerformed
        if (mapAtual==null) return;
        JFileChooser fc = new JFileChooser();
        String[] stArquivosTipos = {".jrcmaps"};
        fc.setFileFilter(new selecaoTipoArquivo(stArquivosTipos));
        fc.setAcceptAllFileFilterUsed(false);
        
        if (fc.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                PrintWriter out = null;
                try {
                    String nomeArquivo = fc.getSelectedFile().getCanonicalPath();
                    if (nomeArquivo.indexOf(".jrcmaps")==-1){
                        nomeArquivo+=".jrcmaps";
                    }
                    out = new PrintWriter(new FileWriter(nomeArquivo));

                    out.println("versao;1");
                    out.println("tamanho;" + qtdLinhas+ ";"+ qtdColunas);
                    StringBuilder stMatriz = new StringBuilder();
                    for (int i=0; i<qtdLinhas;i++)
                        for(int j=0;j<qtdColunas;j++){
                            stMatriz.append(mapAtual[i][j].getValor()).append(";");
                        }
                    
                    out.println("matriz;" + stMatriz.toString());                    

                    out.close();
                } catch (FileNotFoundException ex) {
                    System.out.println(ex.getMessage() + " " + "Arquivo Não Encontrado");
                } catch (IOException ex)    {
                    System.out.println(ex.getMessage() + " " + "Erro ao Gravar o Arquivo");
                } finally {
                    try {
                        out.close();
                    } catch (Exception ex) {
                        System.out.println(ex.getMessage() + " " + "Erro ao Fechar o Arquivo");
                    }
                }
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_mnuSalvarActionPerformed

    private void mnuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbrirActionPerformed
    JFileChooser fc = new JFileChooser();
    
    fc.setCurrentDirectory(new File(stCaminhoMapas));
    
    String[] stArquivosTipos = {".jrcmaps"};
    fc.setFileFilter(new selecaoTipoArquivo(stArquivosTipos));
    fc.setAcceptAllFileFilterUsed(false);
    
    if (fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        File Arquivo = fc.getSelectedFile();                   
        
         try {
              
             stCaminhoMapas = Arquivo.getAbsolutePath();
             savePropriedades();
              
              BufferedReader in = new BufferedReader(new FileReader(Arquivo));
              String str;
              while ((str = in.readLine()) != null) {
                  if (str.length()!=0){
                      String[] vetor = str.split(";");
                      if (vetor!=null && vetor.length>0){
                          if (vetor[0].equalsIgnoreCase("version")){
                              
                          }else if (vetor[0].equalsIgnoreCase("tamanho")){
                              txtLargura.setText(vetor[2]);
                              txtAltura.setText(vetor[1]);  
                              txtLargura.setEditable(false);
                              txtAltura.setEditable(false);
                              prepararMapa();
                          }else if (vetor[0].equalsIgnoreCase("matriz")){
//                              for (int i=0; i<inLargura;i++) 
//                              for(int j=0;j<inAltura;j++){
//                                    tela[i][j].setValor(Integer.valueOf(vetor[((i*inLargura)+(j*inAltura))+1]));
//                                } 
                            int inConte=1;
                            for (int i=0; i<qtdLinhas;i++) 
                              for(int j=0;j<qtdColunas;j++){
                                    mapAtual[i][j].setImagem(Byte.valueOf(vetor[inConte++]));
                                } 
                            panPrincipal.repaint();   
                          }
                      }
                  }
              }
              in.close();
          } catch (Exception e) {   
          
          }
              
    }
    this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAbrirActionPerformed


    private void butCarregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCarregadorActionPerformed
               
        Valor = Ambiente.CARREGADOR;
    }//GEN-LAST:event_butCarregadorActionPerformed

    private void butMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMetalActionPerformed
        
        Valor = Ambiente.METAL;
    }//GEN-LAST:event_butMetalActionPerformed

    private void butOrganicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOrganicoActionPerformed
        
        Valor = Ambiente.ORGANICO;
    }//GEN-LAST:event_butOrganicoActionPerformed

    private void butPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPapelActionPerformed
        
        Valor = Ambiente.PAPEL;
    }//GEN-LAST:event_butPapelActionPerformed

    private void butPlasticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPlasticoActionPerformed
        
        Valor = Ambiente.PLASTICO;
    }//GEN-LAST:event_butPlasticoActionPerformed

    private void butVidroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVidroActionPerformed
        
        Valor = Ambiente.VIDRO;
    }//GEN-LAST:event_butVidroActionPerformed

    private void butChaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butChaoActionPerformed
        
        Valor = Ambiente.CHAO;
    }//GEN-LAST:event_butChaoActionPerformed

    private void butMetalAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMetalAmareloActionPerformed
        
        Valor = Ambiente.COLETOR_METAL_AMARELA;
    }//GEN-LAST:event_butMetalAmareloActionPerformed

    private void butBordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBordaActionPerformed
        
        Valor = Ambiente.BORDA;
    }//GEN-LAST:event_butBordaActionPerformed

    private void butOrganicoMaromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOrganicoMaromActionPerformed
        
        Valor = Ambiente.COLETOR_ORGANICO_MAROM;
    }//GEN-LAST:event_butOrganicoMaromActionPerformed

    private void butPapelAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPapelAzulActionPerformed
        
        Valor = Ambiente.COLETOR_PAPEL_AZUL;
    }//GEN-LAST:event_butPapelAzulActionPerformed

    private void butPlasticoVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPlasticoVermelhoActionPerformed
        
        Valor = Ambiente.COLETOR_PLASTICO_VERMELHA;
    }//GEN-LAST:event_butPlasticoVermelhoActionPerformed

    private void butVidroVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVidroVerdeActionPerformed
        
        Valor = Ambiente.COLETOR_VIDRO_VERDE;
    }//GEN-LAST:event_butVidroVerdeActionPerformed

    private void butObstaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butObstaculoActionPerformed
        
        Valor = Ambiente.OBSTACULO;
    }//GEN-LAST:event_butObstaculoActionPerformed

    private void mnuCarregarRoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCarregarRoboActionPerformed
    
        if (mapAtual==null){
            labMensagem.setText("Carregue primeiro um mapa" );
            return;
        }
        
        final JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(stCaminhoRobo));
        
        String[] stArquivosTipos = {".jar"};
        fc.setFileFilter(new selecaoTipoArquivo(stArquivosTipos));
        fc.setAcceptAllFileFilterUsed(false);
        
        if (fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){             
            stCaminhoRobo = fc.getSelectedFile().getAbsolutePath();
            savePropriedades();                                        
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new fraExecucao( fc.getSelectedFile().getAbsolutePath() ).setVisible(true);
                }
            });
                
        
        }
               
    }//GEN-LAST:event_mnuCarregarRoboActionPerformed

    private void butRoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRoboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butRoboActionPerformed

    private void mnuAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAvaliarActionPerformed
        if (mapAtual==null){
            labMensagem.setText("Carregue primeiro um mapa" );
            return;
        }
        
        final JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(stCaminhoRobo));
        
        String[] stArquivosTipos = {".jar"};
        fc.setFileFilter(new selecaoTipoArquivo(stArquivosTipos));
        fc.setAcceptAllFileFilterUsed(false);
        
        if (fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){             
            stCaminhoRobo = fc.getSelectedFile().getAbsolutePath();
            savePropriedades();                                        
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new fraAvaliar( fc.getSelectedFile().getAbsolutePath() ).setVisible(true);
                }
            });
                
        
        }
    }//GEN-LAST:event_mnuAvaliarActionPerformed

    private void panPrincipalComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panPrincipalComponentResized
        int LarguraAltura;
        
        int altura = (int) ((panPrincipal.getHeight()*0.99)/qtdLinhas);
        int largura = (int) ((panPrincipal.getWidth()*0.99)/qtdColunas);        
                                
        if (altura<largura){
            LarguraAltura = altura;
        }else{
            LarguraAltura = largura;
        }
        
        for (int i=0;i<qtdLinhas; i++)
            for (int j=0;j<qtdColunas;j++){                               
                mapAtual[i][j].setBounds((j*LarguraAltura)+11,(i*LarguraAltura)+31, LarguraAltura,LarguraAltura);                                                                                                    
                mapAtual[i][j].setIcon(Funcoes.getScaledImage( Imagens[mapAtual[i][j].getValor()],mapAtual[i][j].getWidth(),mapAtual[i][j].getHeight()));
            }
        
        panPrincipal.repaint();
    }//GEN-LAST:event_panPrincipalComponentResized

MouseAdapter clickBotao =  new MouseAdapter() {
    public void mousePressed(MouseEvent e) {
        MyTela tela = (MyTela) e.getSource();
        if (!tela.isFixo()){
            tela.setImagem(Valor);
            //tela.setIcon(getScaledImage( Imagem,tela.getWidth(),tela.getHeight()));
        }
    }
};
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fraPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton butBorda;
    private javax.swing.JToggleButton butCarregador;
    private javax.swing.JToggleButton butChao;
    private javax.swing.JButton butGerar;
    private javax.swing.JToggleButton butMetal;
    private javax.swing.JToggleButton butMetalAmarelo;
    private javax.swing.JToggleButton butObstaculo;
    private javax.swing.JToggleButton butOrganico;
    private javax.swing.JToggleButton butOrganicoMarom;
    private javax.swing.JToggleButton butPapel;
    private javax.swing.JToggleButton butPapelAzul;
    private javax.swing.JToggleButton butPlastico;
    private javax.swing.JToggleButton butPlasticoVermelho;
    private javax.swing.JToggleButton butRobo;
    private javax.swing.JToggleButton butVidro;
    private javax.swing.JToggleButton butVidroVerde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labMensagem;
    private javax.swing.JMenuItem mnuAbrir;
    private javax.swing.JMenu mnuAquivo;
    private javax.swing.JMenuItem mnuAvaliar;
    private javax.swing.JMenuItem mnuCarregarRobo;
    private javax.swing.JMenuItem mnuNovo;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenuItem mnuSalvar;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.ButtonGroup radComandos;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtLargura;
    // End of variables declaration//GEN-END:variables
}
